name: Build Next app
on: 
  push:
    branches: [master]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2

      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 16          

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Login to Docker Portal
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nextjs-docker .

      - name: Push to Docker hub
        run: docker image push ${{ secrets.DOCKER_USERNAME }}/nextjs-docker
