name: Build Next app
on: 
  push:
    branches: [master]

jobs:
  test: 
    name: Test OS ${{ matrix.os }} / Node ${{ matrix.node }} 
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        node: ['14.x', '16.x', '18.x']
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Run Tests
        run: npm ci && npm test

  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2

      - name: Setup environment
        uses: actions/setup-node@v3
        with:
          node-version: 16          

      - name: Install dependencies
        run: npm ci
      - name: Login to Docker Portal
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nextjs-docker .

      - name: Push to Docker hub
        run: docker image push ${{ secrets.DOCKER_USERNAME }}/nextjs-docker
